services:
  - type: web
    name: brain-tumor-prediction-by-saketh
    env: python
    region: oregon
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    autoDeploy: true
    envVars:
      - key: PORT
        value: "8501"
